function g = sfun_g(in1)
%SFUN_G
%    G = SFUN_G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    12-Apr-2014 18:47:59

g = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.27e2./1.8e1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.27e2./1.8e1],[10, 2]);
