function P_s = sfun_P(t)
%SFUN_P
%    P_S = SFUN_P(T)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    12-Apr-2014 18:47:59

t2 = pi.*t.*(1.0./2.0);
t3 = pi.*t;
t4 = pi.*t.*(3.0./2.0);
t5 = sin(t2);
t6 = cos(t2);
t7 = sin(t3);
t8 = cos(t3);
t9 = sin(t4);
t10 = cos(t4);
P_s = reshape([1.0,0.0,t5,0.0,t6,0.0,t7,0.0,t8,0.0,t9,0.0,t10,0.0,0.0,1.0,0.0,t5,0.0,t6,0.0,t7,0.0,t8,0.0,t9,0.0,t10],[2, 14]);
