function P_s = sfun_P(t)
%SFUN_P
%    P_S = SFUN_P(T)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    30-Mar-2014 00:24:35

t2 = pi.*t.*(1.0./2.0);
t3 = pi.*t;
t4 = sin(t2);
t5 = cos(t2);
t6 = sin(t3);
t7 = cos(t3);
P_s = reshape([1.0,0.0,t4,0.0,t5,0.0,t6,0.0,t7,0.0,0.0,1.0,0.0,t4,0.0,t5,0.0,t6,0.0,t7],[2, 10]);
