function P_s = sfun_P(t)
%SFUN_P
%    P_S = SFUN_P(T)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    29-Mar-2014 22:17:59

t2 = pi.*t.*(1.0./2.0);
P_s = reshape([1.0,0.0,sin(t2),0.0,cos(t2),0.0,0.0,1.0],[2, 4]);
