function g = sfun_g(in1)
%SFUN_G
%    G = SFUN_G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    29-Mar-2014 22:17:59

g = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.275981111111111e-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.275981111111111e-1],[10, 2]);
