function g = sfun_g(in1)
%SFUN_G
%    G = SFUN_G(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    30-Mar-2014 00:24:35

g = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.275981111111111e-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.275981111111111e-1],[10, 2]);
