function C_lin = sfun_C(in1)
%SFUN_C
%    C_LIN = SFUN_C(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    26-Mar-2014 20:33:11

C_lin = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0e2./7.3e1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3, 10]);
