function P_s = sfun_P(t)
%SFUN_P
%    P_S = SFUN_P(T)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    09-Mar-2014 17:44:10

t2 = pi.*t.*(1.0./2.0);
t3 = pi.*t;
t4 = pi.*t.*(3.0./2.0);
t5 = pi.*t.*2.0;
t6 = sin(t2);
t7 = cos(t2);
t8 = sin(t3);
t9 = cos(t3);
t10 = sin(t4);
t11 = cos(t4);
t12 = sin(t5);
t13 = cos(t5);
P_s = reshape([1.0,0.0,t6,0.0,t7,0.0,t8,0.0,t9,0.0,t10,0.0,t11,0.0,t12,0.0,t13,0.0,0.0,1.0,0.0,t6,0.0,t7,0.0,t8,0.0,t9,0.0,t10,0.0,t11,0.0,t12,0.0,t13],[2, 18]);
