function k = sfun_k(in1)
%SFUN_K
%    K = SFUN_K(IN1)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    08-Apr-2014 11:46:18

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
k = [q1;q2;q3];
